# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_location', models.IntegerField(choices=[(1, 'Wilkinstown, Co.Meath'), (2, 'Navan, Co. Meath')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.Location'),
            preserve_default=False,
        ),
    ]
