# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180602_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
