# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180602_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('price', models.IntegerField(choices=[(10, 'Basic'), (20, '2'), (30, '3'), (40, '4'), (50, '5'), (60, '6'), (70, '7'), (80, '8'), (90, '9'), (100, '10'), (110, '11'), (150, '12'), (180, '13')], default=1)),
            ],
        ),
    ]
