# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='price',
            field=models.IntegerField(choices=[(10, '€10.00'), (20, '€20.00'), (30, '€30.00'), (40, '€40.00'), (50, '€50.00'), (60, '€60.00'), (70, '€70.00'), (80, '€80.00'), (90, '€90.00'), (100, '€100.00'), (110, '€110.00'), (150, '€120.00'), (180, '€130.00')], default=1),
        ),
    ]
