# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180611_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
