# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180611_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
