# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delete_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='home/images/car3.jpeg', upload_to='images'),
        ),
    ]
