# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reservation_guests',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reservation_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reservation_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
    ]
